### ISSUE TITLE
audio not getting uploaded

### ISSUE THREAD

**Issue by rahulbanwasi** [revantkumargupta/AppleMusicTelegrambot#12]
Traceback (most recent call last):
  File "core.py", line 130, in download_music
    bot.send_audio(message.chat.id, f)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 1925, in send_audio
    apihelper.send_audio(
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 893, in send_audio
    return _make_request(token, method_url, params=payload, files=files, method='post')
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 413. Description: Request Entity Too Large

**Comment by revantkumargupta** [comment]
@tonystarkrevant

Contact me here
