### ISSUE TITLE
not working still

### ISSUE THREAD

**Issue by rahulbanwasi** [revantkumargupta/AppleMusicTelegrambot#13]
Successfully installed protobuf-4.25.3
ubuntu@instance-20240320-1402:~/aplbot$ python3 core.py
Traceback (most recent call last):
  File "/home/ubuntu/aplbot/core.py", line 4, in <module>
    from gamdl import Gamdl
  File "/home/ubuntu/aplbot/gamdl/__init__.py", line 5, in <module>
    from .gamdl import Gamdl
  File "/home/ubuntu/aplbot/gamdl/gamdl.py", line 15, in <module>
    from pywidevine import PSSH, Cdm, Device, WidevinePsshData
ImportError: cannot import name 'WidevinePsshData' from 'pywidevine' (/home/ubuntu/.local/lib/python3.10/site-packages/pywidevine/__init__.py)

**Comment by revantkumargupta** [comment]
Use older version of pywidevine in requirements.txt

pywidevine==1.6.0

I have updated the requirements.txt

Try now
